#!/bin/bash
# -----------------------------------------------------------------------------
set -euo pipefail # Stop running the script on first error...
# -----------------------------------------------------------------------------
remote_addr="pi@192.168.1.61"
remote_path="/home/pi/.pi-toolkit"

read -p "SSH Hostname (default: ${remote_addr}): " hostname
if [ -z hostname ]
then
    remote_addr=${hostname}
fi

zip_file="payload.tar.gz"
tar -czvf ${zip_file} \
    --exclude=/proc \
    --exclude=/lost+found \
    --exclude=/sys \
    --exclude=/mnt \
    --exclude=/media \ 
    --exclude=/dev \
    --exclude=/share/Archive \
    ./
ssh ${remote_addr} "cat - > /tmp/${zip_file}; tar -czvf /tmp/${zip_file} ${remote_path}; rm /tmp/${zip_file};" < ${zip_file}
exit 0;

# found=$(ssh ${remote_addr} "[ -d ${remote_path} ] && echo Y || echo N")
# if [ ! "${found}" == "Y" ]
# then
#     echo "Copying local folder to remote..."
#     echo " - Source: $(pwd)..."
#     echo " - Target: ${remote_path}..."
#     scp -r $(pwd) ${remote_addr}:${remote_path}
# fi
