#!/bin/bash
# -----------------------------------------------------------------------------
set -euo pipefail # Stop running the script on first error...
# -----------------------------------------------------------------------------
# Enables remote SSH access to the rasberry pi device
# See also: https://www.raspberrypi.org/documentation/remote-access/ssh/

sudo systemctl enable ssh
sudo systemctl start ssh

# -----------------------------------------------------------------------------
# While we are on the device, lets get the local SSH address (note it down for later):
# -----------------------------------------------------------------------------
HOST=$(hostname -I | cut -d ' ' -f1)
BOLD="\e[1m"
NONE="\e[0m"
WHITE="\e[97m"
SILVER="\e[37m"
BRIGHT="\e[1m"
BLUE="\e[34m"
YELLOW="\e[33m"
DEBUG="\e[90m"
UNDERLINE="\e[4m"
ARGS="\e[95m"
LINK="${UNDERLINE}${BLUE}${BRIGHT}"
TITLE="${UNDERLINE}${WHITE}${BRIGHT}${BOLD}"
WARN="${BRIGHT}${BOLD}${YELLOW}"
printf "
${DEBUG}${UNDERLINE}If you are using a VM (like VirtualBox), you need to set your network settings...${NONE}${DEBUG}
In VirtualBox, go to:
-> Settings -> Network -> Adapter 1 
-> Choose 'Host-only adapter' 
-> OK ${NONE}

${TITLE}You can connect with a remote SSH agent to this device at:${NONE}\n
${DEBUG} -> ${SILVER}ssh ${LINK}${USER}@${HOST}${NONE} ${DEBUG}[ ${ARGS}<command>${DEBUG} ] ${NONE}

${DEBUG}  # Alternatively, open a remote vscode development environment on the device
${DEBUG} -> ${SILVER}code --remote ssh-remote+${LINK}${USER}@${HOST}${NONE} ${BOLD}${ARGS}/home/pi/${NONE}

"