#!/bin/bash
# -----------------------------------------------------------------------------
set -euo pipefail # Stop running the script on first error...
# -----------------------------------------------------------------------------

# Update if not updated in the last week
[ -z "$(find -H /var/lib/apt/lists -maxdepth 0 -mtime -7)" ] \
    && sudo apt update \
    && sudo apt upgrade

# Install the build essentials and module assistant required modules
dpkg -s virtualbox-guest-dkms > /dev/null \
    || sudo apt-get install build-essential module-assistant \
    && sudo m-a prepare \
    && read -p "Insert the VirtualBox guest addons, then press any key to continue..." reply \
    && sudo sh /media/cdrom/VBoxLinuxAdditions.run \
    && sudo adduser pi vboxsf \
    && read -p "Server needs to reboot... Continue? [y|n]" reply \
    && [ "${reply}" == "n" ] || sudo reboot

